### ISSUE TITLE
Download binaries is broken 

### ISSUE THREAD

**Issue by pavolloffay** [jaegertracing/documentation#229]
This is a link to download linux binaries for 1.10: 

https://github.com/jaegertracing/jaeger/releases/download/v%25!s%28%3cnil%3e%29/jaeger-%25!s%28%3cnil%3e%29-linux-amd64.tar.gz

https://www.jaegertracing.io/download/

**Comment by yurishkuro** [comment]
cc @lucperkins

**Comment by yurishkuro** [comment]
btw, @pavolloffay , we didn't do 1.11 docs update

**Comment by pavolloffay** [comment]
The 1.11 PR is open https://github.com/jaegertracing/documentation/pull/228

**Comment by lucperkins** [comment]
@pavolloffay @yurishkuro I don't think there's really any way to explain it except for a spurious build error in the deploy preview. I think that PR #230 worked simply because it triggered a re-build and thus overwrote the broken build. I would recommend undoing the changes in #230 for the sake of consistency (although it's not urgent and the `.Site` syntax is backwards compatible).

**Comment by yurishkuro** [comment]
@lucperkins I reverted the change locally and ran `make develop` and the Downloads page came up broken again. I have
```
$ hugo version
Hugo Static Site Generator v0.53/extended darwin/amd64 BuildDate: unknown
```

**Comment by yurishkuro** [comment]
Another issue #232  due to .Site -> site change

**Comment by jpkrohling** [comment]
I'm closing this, as it seems to have been fixed: the links to the Linux binaries are working (v1.13.0)
