### ISSUE TITLE
The footer should not be covering sidebar menus

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/documentation#745]
When scrolling a docs page all the way up, the footer comes up and covers parts of the left and right sidebar menus.

<img width="1890" alt="image" src="https://github.com/user-attachments/assets/6a084a24-61cb-4c95-8da8-fb69d9a4e13b">

In contrast, in the OTEL docs the scrolling in that situation starts moving up the sidebars as well, so that they are not covered.

<img width="1899" alt="image" src="https://github.com/user-attachments/assets/77fc65fc-6170-4456-acc1-8231f96949cf">

**Comment by willcoderhz** [comment]
I can fix this:))

**Comment by Abhay-hack** [comment]
Could you please assign this issue. I'm a frontend developer and I'm sure that I can fix this issue.

**Comment by 141AQUA-xzy** [comment]
I've fixed it....and it has been tested working in production,please guide me how would jaeger likes to markup with the changes.

Also I found more bugs on the production build and as usual I fixed them.
One such bug was related to the middle column above the footer....and more such are their..........to be cautious of snatchers,we should better connect , so that I could show up the fixed bug & more mentioned optimisations.


E-mail : auraoair@gmail.com
LinkediN : Aura Z
